export const CHANGE_SCREEN = 'CHANGE_SCREEN';

export const CHANGE_PHONE = 'CHANGE_PHONE';

export const SET_USER_INFO = 'SET_USER_INFO';

export const SET_ORDER_START_POINT = 'SET_ORDER_START_POINT';

export const SET_ORDER_END_POINTS = 'SET_ORDER_END_POINTS';

export const SET_ORDER_PRICE = 'SET_ORDER_PRICE';

export const SET_ORDER_ENTRANCE= 'SET_ORDER_ENTRANCE';

export const SET_ORDER_COMMENT= 'SET_ORDER_COMMENT';

export const SET_DEVICE_ID = 'SET_DEVICE_ID';

export const SET_TRADE_LIST = 'SET_TRADE_LIST';

export const SET_FAVORITES_POINTS = 'SET_FAVORITES_POINTS';

export const SET_ORDER = 'SET_ORDER';

export const DRIVER_LOCATION_UPDATE = 'DRIVER_LOCATION_UPDATE';

export const DRIVER_MENU_PUSH = 'DRIVER_MENU_PUSH';

export const SET_DRIVER_INFO = 'SET_DRIVER_INFO';

export const CLEAR_DRIVER_INFO = 'CLEAR_DRIVER_INFO';

export const CLEAR_ORDER_INFO = 'CLEAR_ORDER_INFO';

