export const SET_ORDER = 'SET_ORDER';

export const REMOVE_ORDER = 'REMOVE_ORDER';

export const SET_ORDER_START_POINT = 'SET_ORDER_START_POINT';

export const SET_ORDER_END_POINT = 'SET_ORDER_END_POINT';

export const SET_ORDER_PRICE = 'SET_ORDER_PRICE';

export const SET_ORDER_ENTRANCE = 'SET_ORDER_ENTRANCE';

export const SET_ORDER_COMMENT = 'SET_ORDER_COMMENT';

export const SET_ORDER_WAY_POINT = 'SET_ORDER_WAY_POINT_END_POINT';

export const ADD_ORDER_WAY_POINT = 'ADD_ORDER_WAY_POINT_END_POINT';

export const REMOVE_ORDER_WAY_POINT = 'REMOVE_ORDER_WAY_POINT_END_POINT';

export const SET_ORDER_OPTIONS = 'SET_ORDER_OPTIONS';

export const SET_ORDER_CAR_TYPE = 'SET_ORDER_CAR_TYPE';

export const SET_CARD_ID = 'SET_CARD_ID';
